### ISSUE TITLE
jupyter notebook: kernel dies running cifar10_cnn.py

### ISSUE THREAD

**Issue by jpaos** [ROCmSoftwarePlatform/tensorflow#23]
The example cifar10_cnn.py (https://raw.githubusercontent.com/keras-team/keras/master/examples/cifar10_cnn.py) works fine when I run it from terminal: ` python3 cifar10_cnn.py`
However, when I put the code inside a notebook cell, I get "The kernel appears to have died. It will restart automatically." 

This is the log I see in terminal:

```
[I 23:00:54.304 NotebookApp] Kernel started: 383bb4ce-8bbc-4845-ab5d-f00cb8bcae8c
[I 23:00:55.043 NotebookApp] Adapting to protocol v5.1 for kernel 383bb4ce-8bbc-4845-ab5d-f00cb8bcae8c
2018-03-26 23:01:23.795319: W tensorflow/stream_executor/rocm/rocm_driver.cc:405] creating context when one is currently active; existing: 0x7fa6daf2fbd0
2018-03-26 23:01:23.795717: I tensorflow/core/common_runtime/gpu/gpu_device.cc:907] Found device 0 with properties: 
name: Fiji [Radeon R9 FURY / NANO Series]
AMDGPU ISA: gfx803
memoryClockRate (GHz) 1
pciBusID 0000:21:00.0
Total memory: 4.00GiB
Free memory: 3.75GiB
2018-03-26 23:01:23.795782: W tensorflow/stream_executor/rocm/rocm_driver.cc:405] creating context when one is currently active; existing: 0x7fa6daf368b0
2018-03-26 23:01:23.795857: I tensorflow/core/common_runtime/gpu/gpu_device.cc:907] Found device 1 with properties: 
name: Fiji [Radeon R9 FURY / NANO Series]
AMDGPU ISA: gfx803
memoryClockRate (GHz) 1
pciBusID 0000:31:00.0
Total memory: 4.00GiB
Free memory: 3.75GiB
2018-03-26 23:01:23.795896: I tensorflow/core/common_runtime/gpu/gpu_device.cc:801] Peer access not supported between device ordinals 0 and 1
2018-03-26 23:01:23.795906: I tensorflow/core/common_runtime/gpu/gpu_device.cc:801] Peer access not supported between device ordinals 1 and 0
2018-03-26 23:01:23.795921: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929] DMA: 0 1 
2018-03-26 23:01:23.795928: I tensorflow/core/common_runtime/gpu/gpu_device.cc:939] 0:   Y N 
2018-03-26 23:01:23.795936: I tensorflow/core/common_runtime/gpu/gpu_device.cc:939] 1:   N Y 
2018-03-26 23:01:23.795946: I tensorflow/core/common_runtime/gpu/gpu_device.cc:997] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Fiji [Radeon R9 FURY / NANO Series], pci bus id: 0000:21:00.0)
2018-03-26 23:01:23.795954: I tensorflow/core/common_runtime/gpu/gpu_device.cc:997] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Fiji [Radeon R9 FURY / NANO Series], pci bus id: 0000:31:00.0)
2018-03-26 23:01:24.423778: I tensorflow/core/kernels/conv_ops.cc:670] running auto-tune for Convolve
```
From terminal:

```
jpaos@faraday:~/python$ python3 cifar10_cnn.py 
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
x_train shape: (50000, 32, 32, 3)
50000 train samples
10000 test samples
Using real-time data augmentation.
Epoch 1/100
2018-03-26 23:03:06.518172: W tensorflow/stream_executor/rocm/rocm_driver.cc:405] creating context when one is currently active; existing: 0x7f48faa96e50
2018-03-26 23:03:06.518406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:907] Found device 0 with properties: 
name: Fiji [Radeon R9 FURY / NANO Series]
AMDGPU ISA: gfx803
memoryClockRate (GHz) 1
pciBusID 0000:21:00.0
Total memory: 4.00GiB
Free memory: 3.75GiB
2018-03-26 23:03:06.518468: W tensorflow/stream_executor/rocm/rocm_driver.cc:405] creating context when one is currently active; existing: 0x7f48faa9db30
2018-03-26 23:03:06.518534: I tensorflow/core/common_runtime/gpu/gpu_device.cc:907] Found device 1 with properties: 
name: Fiji [Radeon R9 FURY / NANO Series]
AMDGPU ISA: gfx803
memoryClockRate (GHz) 1
pciBusID 0000:31:00.0
Total memory: 4.00GiB
Free memory: 3.75GiB
2018-03-26 23:03:06.518580: I tensorflow/core/common_runtime/gpu/gpu_device.cc:801] Peer access not supported between device ordinals 0 and 1
2018-03-26 23:03:06.518591: I tensorflow/core/common_runtime/gpu/gpu_device.cc:801] Peer access not supported between device ordinals 1 and 0
2018-03-26 23:03:06.518634: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929] DMA: 0 1 
2018-03-26 23:03:06.518643: I tensorflow/core/common_runtime/gpu/gpu_device.cc:939] 0:   Y N 
2018-03-26 23:03:06.518650: I tensorflow/core/common_runtime/gpu/gpu_device.cc:939] 1:   N Y 
2018-03-26 23:03:06.518663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:997] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Fiji [Radeon R9 FURY / NANO Series], pci bus id: 0000:21:00.0)
2018-03-26 23:03:06.518673: I tensorflow/core/common_runtime/gpu/gpu_device.cc:997] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Fiji [Radeon R9 FURY / NANO Series], pci bus id: 0000:31:00.0)
2018-03-26 23:03:07.141751: I tensorflow/core/kernels/conv_ops.cc:670] running auto-tune for Convolve
2018-03-26 23:03:07.510136: I tensorflow/core/kernels/conv_ops.cc:670] running auto-tune for Convolve
2018-03-26 23:03:07.574726: I tensorflow/core/kernels/conv_ops.cc:670] running auto-tune for Convolve
2018-03-26 23:03:07.575899: I tensorflow/core/kernels/conv_ops.cc:670] running auto-tune for Convolve
2018-03-26 23:03:07.646637: I tensorflow/core/kernels/conv_grad_input_ops.cc:858] running auto-tune for Backward-Data
2018-03-26 23:03:07.720131: I tensorflow/core/kernels/conv_grad_filter_ops.cc:778] running auto-tune for Backward-Filter
2018-03-26 23:03:07.785053: I tensorflow/core/kernels/conv_grad_input_ops.cc:858] running auto-tune for Backward-Data
2018-03-26 23:03:07.786332: I tensorflow/core/kernels/conv_grad_filter_ops.cc:778] running auto-tune for Backward-Filter
2018-03-26 23:03:07.849565: I tensorflow/core/kernels/conv_grad_input_ops.cc:858] running auto-tune for Backward-Data
2018-03-26 23:03:07.916088: I tensorflow/core/kernels/conv_grad_filter_ops.cc:778] running auto-tune for Backward-Filter
2018-03-26 23:03:07.975020: I tensorflow/core/kernels/conv_grad_filter_ops.cc:778] running auto-tune for Backward-Filter
  99/1563 [>.............................] - ETA: 47s - loss: 2.2645 - acc: 0.14742018-03-26 23:03:09.639216: I tensorflow/core/kernels/conv_ops.cc:670] running auto-tune for Convolve
2018-03-26 23:03:09.707448: I tensorflow/core/kernels/conv_ops.cc:670] running auto-tune for Convolve
2018-03-26 23:03:09.765801: I tensorflow/core/kernels/conv_ops.cc:670] running auto-tune for Convolve
2018-03-26 23:03:09.766236: I tensorflow/core/kernels/conv_ops.cc:670] running auto-tune for Convolve
2018-03-26 23:03:09.834234: I tensorflow/core/kernels/conv_grad_input_ops.cc:858] running auto-tune for Backward-Data
2018-03-26 23:03:09.906494: I tensorflow/core/kernels/conv_grad_filter_ops.cc:778] running auto-tune for Backward-Filter
2018-03-26 23:03:09.968976: I tensorflow/core/kernels/conv_grad_input_ops.cc:858] running auto-tune for Backward-Data
2018-03-26 23:03:09.969769: I tensorflow/core/kernels/conv_grad_filter_ops.cc:778] running auto-tune for Backward-Filter
2018-03-26 23:03:10.031834: I tensorflow/core/kernels/conv_grad_input_ops.cc:858] running auto-tune for Backward-Data
2018-03-26 23:03:10.097919: I tensorflow/core/kernels/conv_grad_filter_ops.cc:778] running auto-tune for Backward-Filter
2018-03-26 23:03:10.155317: I tensorflow/core/kernels/conv_grad_filter_ops.cc:778] running auto-tune for Backward-Filter
 246/1563 [===>..........................] - ETA: 32s - loss: 2.1577 - acc: 0.1937^CTraceback (most recent call last):
...

```

**Comment by whchung** [comment]
@jpaos Please help elaborate what do you mean by "notebook cell". And please check https://github.com/ROCmSoftwarePlatform/tensorflow/blob/rocm-v1/README.ROCm.md#x-freezes-under-load and see if you are bumping into the same issue.

**Comment by jpaos** [comment]
In the terminal I start a jupyter notebook using `$ jupyter-notebook`. Start a new python3 notebook and insert the code cifar10_cnn.py inside a notebook cell and run it from there.

**Comment by whchung** [comment]
Since you run it within X window I'm suspecting you might run into `noretry=1` bug in AMD graphics driver. Please follow the link above and see if setting `noretry=0` helps.

**Comment by fxkamd** [comment]
The noretry option doesn't affect Fiji GPUs. I think it's more likely that graphics and compute are competing for GPU memory causing evictions. I think the latest ROCm 1.7.1 has some improvements in that area. Are there any kernel log messages about evictions?

**Comment by jpaos** [comment]
Again, when I try that code again from a notebook I get this on kern.log:

Mar 26 23:41:28 faraday kernel: [38662.740793] Evicting PASID 1 queues
Mar 26 23:41:28 faraday kernel: [38662.740834] Evicting PASID 1 queues
Mar 26 23:41:28 faraday kernel: [38662.748047] Restoring PASID 1 queues
Mar 26 23:41:28 faraday kernel: [38662.748058] Restoring PASID 1 queues
Mar 26 23:41:45 faraday kernel: [38679.810068] Evicting PASID 1 queues
Mar 26 23:41:45 faraday kernel: [38679.810116] Evicting PASID 1 queues
Mar 26 23:41:45 faraday kernel: [38679.816180] Restoring PASID 1 queues
Mar 26 23:41:45 faraday kernel: [38679.816200] Restoring PASID 1 queues
Mar 26 23:41:45 faraday kernel: [38679.887789] Evicting PASID 1 queues
Mar 26 23:41:45 faraday kernel: [38679.887823] Evicting PASID 1 queues
Mar 26 23:41:45 faraday kernel: [38679.896156] Restoring PASID 1 queues
Mar 26 23:41:45 faraday kernel: [38679.896177] Restoring PASID 1 queues
Mar 26 23:41:45 faraday kernel: [38679.926025] traps: python3[30343] general protection ip:7f76e9aac908 sp:7f7352ff8f50 error:0 in libstdc++.so.6.0.21[7f76e9a20000+172000]


(by the way, “echo 0 | sudo tee /sys/module/amdkfd/parameters/noretry“ didn’t work)
Again, running the same example from terminal “python3 cifar10_cnn.py” it works and I get this on kern.log:

Mar 26 23:44:06 faraday kernel: [38821.087423] Evicting PASID 1 queues
Mar 26 23:44:06 faraday kernel: [38821.087474] Evicting PASID 1 queues
Mar 26 23:44:06 faraday kernel: [38821.095407] Restoring PASID 1 queues
Mar 26 23:44:06 faraday kernel: [38821.095421] Restoring PASID 1 queues
Mar 26 23:44:07 faraday kernel: [38822.501286] Evicting PASID 1 queues
Mar 26 23:44:07 faraday kernel: [38822.501334] Evicting PASID 1 queues
Mar 26 23:44:07 faraday kernel: [38822.507374] Restoring PASID 1 queues
Mar 26 23:44:07 faraday kernel: [38822.507390] Restoring PASID 1 queues
Mar 26 23:44:07 faraday kernel: [38822.583385] Evicting PASID 1 queues
Mar 26 23:44:07 faraday kernel: [38822.583417] Evicting PASID 1 queues
Mar 26 23:44:07 faraday kernel: [38822.595531] Restoring PASID 1 queues
Mar 26 23:44:07 faraday kernel: [38822.595548] Restoring PASID 1 queues
Mar 26 23:44:15 faraday kernel: [38830.044829] Evicting PASID 1 queues
Mar 26 23:44:15 faraday kernel: [38830.044858] Evicting PASID 1 queues
Mar 26 23:44:15 faraday kernel: [38830.051372] Restoring PASID 1 queues
Mar 26 23:44:15 faraday kernel: [38830.051389] Restoring PASID 1 queues
...

**Comment by fxkamd** [comment]
What is the general protection fault in libstdc++? That's in a python3 process. Is that the problem you're trying to solve? Any chance you can capture a backtrace of that?

**Comment by jpaos** [comment]
How can I get a backtrace?
I don’t know if this is my problem. When I run the code inside a notebook the "kernel dies”. Just says that…
From terminal, it works fine.

**Comment by fxkamd** [comment]
You'd need to attache a gdb to the python3 process before it dies. When it gets the segfault you can get a backtrace with the "bt" command.

**Comment by whchung** [comment]
@streamhsa Please help reproduce the issue.

**Comment by whchung** [comment]
@jpaos I can reproduce the issue. I noticed at `keras` startup there is something weird showing:

```
[7745:7784:0403/093653.974810:ERROR:browser_gpu_channel_host_factory.cc(121)] Failed to launch GPU process.
```

After some quick googling it brought me to:
https://github.com/jupyter/notebook/issues/2836

and `export BROWSER=google-chrome` helped me removing the error.

However the issue still persists. I think I'll need to dive deeper to understand how `keras` launches `TensorFlow` and how `MIOpen` .so is loaded along the way.

**Comment by whchung** [comment]
@fxkamd The issue has nothing to do with `noretry`. From the look of it it has to do with dynamic loading mechanism between `keras` browser session and `TensorFlow` and `MIOpen`.

+ @dagamayank for awareness.

**Comment by whchung** [comment]
After some more fiddling with this example, I found this could make it work:

```

with tf.device('/cpu:0'):
    model.add(Conv2D(32, (3, 3), padding='same',
                     input_shape=x_train.shape[1:]))

with tf.device('/gpu:0'):
    model.add(Activation('relu'))
    model.add(Conv2D(32, (3, 3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))
    model.add(Conv2D(64, (3, 3), padding='same'))
    model.add(Activation('relu'))
    model.add(Conv2D(64, (3, 3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))

    model.add(Flatten())
    model.add(Dense(512))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(num_classes))
    model.add(Activation('softmax'))
```

what happens is `MIOpen` somehow throws an unhandled exception at:
```
    model.add(Conv2D(32, (3, 3), padding='same',
                     input_shape=x_train.shape[1:]))
```
forcing it to CPU temporary workaround the issue. It still needs to be better looked into.

Based on the current observation it makes this issue be related to #16 and #21 . + @sunway513 for awareness.

**Comment by whchung** [comment]
+ @bensander @scchan @pfultz2 @dagamayank for awareness.

The root cause has been figured out. Multiple instances of `libunwind` are loaded at runtime and messed up the exception handling routine. Need to disable `libunwind` dependency across various components within ROCm stack.

**Comment by whchung** [comment]
The issue would be resolved in the next ROCm 1.7.2 release where all `libunwind` dependencies be dropped. We will also publish a new set of PIP wheels.

**Comment by 7SK** [comment]
Hi @jpaos ,
ROCm1.7.2 is released, with it the issue is resolved. Please give it a try.
If you running it with keras-2.1.6, you will get the following error:
TypeError: softmax() got an unexpected keyword argument 'axis'
since latest keras is updated with the latest changes in tensorflow, please use a previous version
pip install --upgrade keras==2.1.3

**Comment by whchung** [comment]
Closing this issue as ROCm 1.7.2 has been released and PIP packages for ROCm 1.7.2 were also released.

**Comment by jpaos** [comment]
@mauriciobreternitz 
@whchung 

We tried the latest version of ROCm 1.7.2 and the problem persists. I finally managed to get a backtrace of the execution of cifar10 inside a jupyter notebook (thanks to Mauricio):
```
#0  0x00007fe0d8075428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fe0d807702a in __GI_abort () at abort.c:89
#2  0x00007fe0d30cf9dd in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fe0d30cfee1 in __gxx_personality_v0 () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fe003189c1e in __libunwind_Unwind_Resume () from /usr/lib/x86_64-linux-gnu/libunwind.so.8
#5  0x00007fe0008ca285 in mlo_construct_direct2D::mloUseSolution(miopen::solver::ConvSolution const&) () from /opt/rocm/lib/libMIOpen.so.1
#6  0x00007fe00093c2ab in miopen::ConvolutionDescriptor::FindWinogradKernel(miopen::Handle&, miopen::TensorDescriptor const&, miopen::TensorDescriptor const&, miopen::TensorDescriptor const&, std::tuple<int, int, int, int, int, int, int, int, int, int, int, int, bool>&, miopen::HIPOCKernelInvoke&, int) const () from /opt/rocm/lib/libMIOpen.so.1
#7  0x00007fe00093ef70 in miopen::ConvolutionDescriptor::FindConvFwdAlgorithm(miopen::Handle&, miopen::TensorDescriptor const&, void const*, miopen::TensorDescriptor const&, void const*, miopen::TensorDescriptor const&, void const*, int, int*, miopenConvAlgoPerf_t*, void*, unsigned long, bool) const () from /opt/rocm/lib/libMIOpen.so.1
#8  0x00007fe0007c8e87 in miopenFindConvolutionForwardAlgorithm () from /opt/rocm/lib/libMIOpen.so.1
#9  0x00007fe007b15b9b in bool perftools::gputools::rocm::MIOpenSupport::DoConvolveImpl<float>(perftools::gputools::Stream*, int, perftools::gputools::dnn::BatchDescriptor const&, perftools::gputools::DeviceMemory<float> const&, perftools::gputools::dnn::FilterDescriptor const&, perftools::gputools::DeviceMemory<float> const&, perftools::gputools::dnn::ConvolutionDescriptor const&, perftools::gputools::DeviceMemory<float> const&, perftools::gputools::dnn::ActivationMode, perftools::gputools::dnn::BatchDescriptor const&, perftools::gputools::DeviceMemory<float>*, perftools::gputools::ScratchAllocator*, perftools::gputools::dnn::AlgorithmConfig const&, perftools::gputools::dnn::ProfileResult*) ()
   from /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#10 0x00007fe007b16059 in perftools::gputools::rocm::MIOpenSupport::DoConvolve(perftools::gputools::Stream*, perftools::gputools::dnn::BatchDescriptor const&, perftools::gputools::DeviceMemory<float> const&, perftools::gputools::dnn::FilterDescriptor const&, perftools::gputools::DeviceMemory<float> const&, perftools::gputools::dnn::ConvolutionDescriptor const&, perftools::gputools::dnn::BatchDescriptor const&, perftools::gputools::DeviceMemory<float>*, perftools::gputools::ScratchAllocator*, perftools::gputools::dnn::AlgorithmConfig const&, perftools::gputools::dnn::ProfileResult*) () from /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#11 0x00007fe009306418 in perftools::gputools::Stream::ThenConvolveWithAlgorithm(perftools::gputools::dnn::BatchDescriptor const&, perftools::gputools::DeviceMemory<float> const&, perftools::gputools::dnn::FilterDescriptor const&, perftools::gputools::DeviceMemory<float> const&, perftools::gputools::dnn::ConvolutionDescriptor const&, perftools::gputools::dnn::BatchDescriptor const&, perftools::gputools::DeviceMemory<float>*, perftools::gputools::ScratchAllocator*, perftools::gputools::dnn::AlgorithmConfig const&, perftools::gputools::dnn::ProfileResult*) ()
   from /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#12 0x00007fe00795c031 in tensorflow::LaunchConv2DOp<Eigen::GpuDevice, float>::launch(tensorflow::OpKernelContext*, bool, bool, tensorflow::Tensor const&, tensorflow::Tensor const&, int, int, Eigen::PaddingType const&, tensorflow::Tensor*, tensorflow::TensorFormat) ()
   from /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#13 0x00007fe0079600c3 in tensorflow::Conv2DOp<Eigen::GpuDevice, float>::Compute(tensorflow::OpKernelContext*) ()
   from /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#14 0x00007fe00796fb49 in tensorflow::BaseGPUDevice::ComputeHelper(tensorflow::OpKernel*, tensorflow::OpKernelContext*) ()
   from /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#15 0x00007fe00796fec0 in tensorflow::BaseGPUDevice::Compute(tensorflow::OpKernel*, tensorflow::OpKernelContext*) ()
   from /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#16 0x00007fe007a3a00b in tensorflow::(anonymous namespace)::ExecutorState::Process(tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, long long) () from /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#17 0x00007fe007a3a26f in std::_Function_handler<void (), tensorflow::(anonymous namespace)::ExecutorState::ScheduleReady(tensorflow::gtl::InlinedVector<tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, 8> const&, tensorflow::(anonymous namespace)::ExecutorState::TaggedNo---Type <return> to continue, or q <return> to quit---
#18 0x00007fe0093a5fc1 in Eigen::NonBlockingThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) ()
   from /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#19 0x00007fe0093a3fa6 in std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#20 0x00007fe0d30fbc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#21 0x00007fe0d84116ba in start_thread (arg=0x7fdd577fe700) at pthread_create.c:333
#22 0x00007fe0d814741d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

We then tried to uninstall everything and reinstall from scratch. However, when executing some of the steps to upgrade 
```
sudo apt-get update && \
    sudo apt-get install -y --allow-unauthenticated \
    rocm-dkms rocm-dev rocm-libs \
    rocm-device-libs \
    hsa-ext-rocr-dev hsakmt-roct-dev hsa-rocr-dev \
    rocm-opencl rocm-opencl-dev \
    rocm-utils \
    rocm-profiler cxlactivitylogger \
    miopen-hip miopengemm
```
we got into this error:

```
update-initramfs: Generating /boot/initrd.img-4.13.0-39-generic
W: Possible missing firmware /lib/firmware/amdgpu/raven_gpu_info.bin for module amdgpu
W: Possible missing firmware /lib/firmware/amdgpu/vega10_gpu_info.bin for module amdgpu
... omitted many lines
```

We thought it was related to the graphics driver. We tried to install the lastest version from here (https://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-for-Linux-Release-Notes.aspx) and the file seems to be corrupted.

```
sha1sum amdgpu-pro-18.10-572953.tar.xz 
5d74c0b130f8b49ee9ad9630ddf01abd8fe8df99  amdgpu-pro-18.10-572953.tar.xz
```
```
tar -Jxvf amdgpu-pro-18.10-572953.tar.xz 
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by whchung** [comment]
@jpaos From the stacktrace you are still using TensorFlow linked with `libunwind`. Please refer to my comment at #21 to make sure everything is in place:

make sure we are using ROCm 1.7.2:

apt show rocm-dkms

should give us 1.7.148

make sure we are using TensorFlow PIP package built for ROCm 1.7.2:

$ md5sum tensorflow-1.3.0-cp35-cp35m-linux_x86_64.whl
f189b887952647db07a7458ea550ca20 tensorflow-1.3.0-cp35-cp35m-linux_x86_64.whl

$ md5sum tensorflow-1.3.0-cp27-cp27mu-linux_x86_64.whl
70c497565f69f0a046ba7ebf80d9d5ee tensorflow-1.3.0-cp27-cp27mu-linux_x86_64.whl

The packages are located at : http://repo.radeon.com/rocm/misc/tensorflow/ . Please help download them and check against MD5 checksum above.

make sure MIOpen kernel caches are wiped out:

rm -rf ~/.cache/miopen

Between ROCm releases OpenCL compiler used to build MIOpen kernels could be different and wiping out MIOpen kernel cache would ensure we always start from a clean slate.

Also amdgpu-pro is NOT required for ROCm.
